global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using VisualStateManagerBugImpl.Models;
global using VisualStateManagerBugImpl.Presentation;
global using VisualStateManagerBugImpl.DataContracts;
global using VisualStateManagerBugImpl.DataContracts.Serialization;
global using VisualStateManagerBugImpl.Services.Caching;
global using VisualStateManagerBugImpl.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
